/** This is the file for mapping names of songs together with picture names */

type ImageMapping = {
    songName: string;
    picName: string;
    path: any; // The `require` function returns an object, so we use `any` here.
    songKey: any;
    number: number;
    flat: any;
  };

  const songNames: string[] = [
    'Mtakatifu', 
    "Twamsifu Mungu", 
    "Mungu atukuzwe",
    "Jina la Yesu salamu",
    "Na tumwabudu Mfalme",
    "Kumekucha kwa Uzuri",
    "Mungu Msaada wetu",
    "Uje MKombozi",
    "Mwumabji, Mfalme",
    "Kristo wa neema",
    "Jina la Bwana li heri",
    "Msifu Mungu wa Neema",
    "Yesu uje kwetu",
    "Nitembee nawe",
    "Nena rohoni Yesu",
    "Bwana ninakuhitaji",
    "Si mimi kristo",
    "Mwokozi kama Mchunga",
    "Msalabani pa Mwokozi",
    "Mungu wetu yeye mwamba",
    "Baba twakujia",
    "Usinipite Mwokozi",
    "Yesu Furaha ya moyo",
    "Jina lake Yesu tamu",
    "Taji mvikeni",
    "Tutokapo tubriki",
    "Tena Mwokozi twalitukuza",
    "Jina la Thamani",
    "Yesu nakupenda U mali",
    "Yesu unipendaye",
    "Niimbe pendo lake",
    "Tangu kuamini",
    "Karibu sana",
    "Nipe Habari za Yesu",
    "Nimekombolewa na Yesu",
    "Siku kuu",
    "Pendo lako ee Mwkozi",
    "Nasifu shani ya Mungu",
    "Ati, kuna mvua njema",
    "Nijaze sasa",
    "Roho Mtakatifu",
    "Ewe roho wa mbinguni",
    "Furaha gani",
    "Hakuna rafiki kama Yesu",
    "Mlimani pana mwanga (Mwanga umo Moyoni)",
    "Miguuni pake Yesu",
    "Ni heri Kifungo",
    "Ninakupenda zaidi",
    "Ninaye rafiki",
    "Mungu awe nanyi daima",
    "Kuwa Na Yesu",
    "Nipe Biblia",
    "Napenda kuhubiri",
    "Nataka nimjue Yesu",
    "Twapanda Mapema",
    "Walio kifoni (Waponyeni watu)",
    "Usikatae kazi yake Bwana",
    "Zitakuwa nyota Tajini",
    "Fanyeni kazi zenu",
    "Nitakwenda Utakaponituma",
    "Bwana nami",
    "Napenda kitabu chake",
    "Niuonapo msalaba",
    "Piga panda ya injili",
    "Twendeni askari",
    "Roho yangu amka sasa",
    "Kesha Roho yangu",
    "Tusimame imara Mwambani",
    "Cha kutumaini sina",
    "Wapenzi wa Bwana",
    "Kesha ukaombe",
    "Jenga juu ya Mwamba",
    "Bwana uniongoze juu",
    "Niambie ee mlinzi",
    "Msingi imara ninyi wa Bwana",
    "Mrithi ufalme",
    "Habari za usiku",
    "Mpaka lini Bwana",
    "Nataka imani hii",
    "Tupe moto wa uhai",
];

// Use static require for images
const images = [
  require('@/assets/songImages/1.jpg'),
  require('@/assets/songImages/2.jpg'),
  require('@/assets/songImages/3.jpg'),
  require('@/assets/songImages/4.jpg'),
  require('@/assets/songImages/5.jpg'),
  require('@/assets/songImages/6.jpg'),
  require('@/assets/songImages/7.jpg'),
  require('@/assets/songImages/8.jpg'),
  require('@/assets/songImages/9.jpg'),
  require('@/assets/songImages/10.jpg'),
  require('@/assets/songImages/11.jpg'),
  require('@/assets/songImages/12.jpg'),
  require('@/assets/songImages/13.jpg'),
  require('@/assets/songImages/14.jpg'),
  require('@/assets/songImages/15.jpg'),
  require('@/assets/songImages/16.jpg'),
  require('@/assets/songImages/17.jpg'),
  require('@/assets/songImages/18.jpg'),
  require('@/assets/songImages/19.jpg'),
  require('@/assets/songImages/20.jpg'),
  require('@/assets/songImages/21.jpg'),
  require('@/assets/songImages/22.jpg'),
  require('@/assets/songImages/23.jpg'),
  require('@/assets/songImages/24.jpg'),
  require('@/assets/songImages/25.jpg'),
  require('@/assets/songImages/26.jpg'),
  require('@/assets/songImages/27.jpg'),
  require('@/assets/songImages/28.jpg'),
  require('@/assets/songImages/29.jpg'),
  require('@/assets/songImages/30.jpg'),
  require('@/assets/songImages/31.jpg'),
  require('@/assets/songImages/32.jpg'),
  require('@/assets/songImages/33.jpg'),
  require('@/assets/songImages/34.jpg'),
  require('@/assets/songImages/35.jpg'),
  require('@/assets/songImages/36.jpg'),
  require('@/assets/songImages/37.jpg'),
  require('@/assets/songImages/38.jpg'),
  require('@/assets/songImages/39.jpg'),
  require('@/assets/songImages/40.jpg'),
  require('@/assets/songImages/41.jpg'),
  require('@/assets/songImages/42.jpg'),
  require('@/assets/songImages/43.jpg'),
  require('@/assets/songImages/44.jpg'),
  require('@/assets/songImages/45.jpg'),
  require('@/assets/songImages/46.jpg'),
  require('@/assets/songImages/47.jpg'),
  require('@/assets/songImages/48.jpg'),
  require('@/assets/songImages/49.jpg'),
  require('@/assets/songImages/50.jpg'),
  require('@/assets/songImages/51.jpg'),
  require('@/assets/songImages/52.jpg'),
  require('@/assets/songImages/53.jpg'),
  require('@/assets/songImages/54.jpg'),
  require('@/assets/songImages/55.jpg'),
  require('@/assets/songImages/56.jpg'),
  require('@/assets/songImages/57.jpg'),
  require('@/assets/songImages/58.jpg'),
  require('@/assets/songImages/59.jpg'),
  require('@/assets/songImages/60.jpg'),
  require('@/assets/songImages/61.jpg'),
  require('@/assets/songImages/62.jpg'),
  require('@/assets/songImages/63.jpg'),
  require('@/assets/songImages/64.jpg'),
  require('@/assets/songImages/65.jpg'),
  require('@/assets/songImages/66.jpg'),
  require('@/assets/songImages/67.jpg'),
  require('@/assets/songImages/68.jpg'),
  require('@/assets/songImages/69.jpg'),
  require('@/assets/songImages/70.jpg'),
  require('@/assets/songImages/71.jpg'),
  require('@/assets/songImages/72.jpg'),
  require('@/assets/songImages/73.jpg'),
  require('@/assets/songImages/74.jpg'),
  require('@/assets/songImages/75.jpg'),
  require('@/assets/songImages/76.jpg'),
  require('@/assets/songImages/77.jpg'),
  require('@/assets/songImages/78.jpg'),
  require('@/assets/songImages/79.jpg'),
  require('@/assets/songImages/80.jpg'),
/*require('@/assets/songImages/1.jpg'),
  require('@/assets/songImages/2.jpg'),
  require('@/assets/songImages/3.jpg'),
  require('@/assets/songImages/4.jpg'),
  require('@/assets/songImages/5.jpg'),
  require('@/assets/songImages/6.jpg'),
  require('@/assets/songImages/7.jpg'),
  require('@/assets/songImages/8.jpg'),
  require('@/assets/songImages/9.jpg'),
  require('@/assets/songImages/10.jpg'),
  require('@/assets/songImages/1.jpg'),
  require('@/assets/songImages/2.jpg'),
  require('@/assets/songImages/3.jpg'),
  require('@/assets/songImages/4.jpg'),
  require('@/assets/songImages/5.jpg'),
  require('@/assets/songImages/6.jpg'),
  require('@/assets/songImages/7.jpg'),
  require('@/assets/songImages/8.jpg'),
  require('@/assets/songImages/9.jpg'),
  require('@/assets/songImages/10.jpg'),*/
];

const songKeys: (string | undefined)[] = [
  'D', 'F', 'G', 'G', 'G', 'Ab', 'C', 'Bb', 'C', 'D',
  'A', 'G', 'G', 'G', 'D', 'G', 'Eb', 'Db', 'Ab', 'F',
  'Eb', 'G', 'A', 'D', 'D', 'Db', 'G', 'Ab', 'F', 'F',
  'Bb', 'F', 'Db', 'D', 'A', 'F', 'Ab', 'C', 'F', 'F',
  'G', 'G', 'Ab', 'G', 'G', 'A', 'F', 'C', 'Ab', 'Bb',
  'Db', 'G', 'G', 'G', 'Bb', 'Bb', 'D', 'G', 'Eb', 'Eb',
  'F', 'F', 'D', 'Ab', 'D', 'F', 'Bb', 'Eb', 'F', 'F',
  'Eb', 'G', 'Ab', 'G', 'G', 'Bb', 'C', 'Ab', 'G', 'Ab',
];
  
  // The function that returns the mapped images
  const mapSongsToImages = (): ImageMapping[] => {  
    // Return the mapped result
    return songNames.map((songName, index) => {
      const originalKey = songKeys[index]; // Can be undefined
      return {
        songName,
        picName: songName.replace(/\s+/g, '_').toLowerCase(), // Make a nice picName
        path: images[index], // The require result
        songKey: originalKey ? originalKey.replace("b", "") : undefined, // Strip 'b' from key
        flat: originalKey ? (originalKey.includes("b") ? true : false) : undefined, // 1 if flat, 0 otherwise, undefined if no key
        number: index + 1,
      };
    });
  };
  
  export default mapSongsToImages;
  